### PR TITLE
Add ability to specify Client ID

### PR DESCRIPTION
**Pull request by rajadain**
Hi!

This PR adds the ability for premium plan users to use their client id, instead of the API Key which is used by regular users. This adds support for a boolean flag that states whether the specified key is a regular key or a client id. The flag should default to false and is not required, thus existing implementations should not break and this should be backward compatible.

Example usage:

``` jsx
<GoogleLayer
    googlekey={googleKey} asclientid
    type={googleMapType}
    mapOptions={{ styles: googleMapStyles }}
/>
```

See here for details: https://developers.google.com/maps/documentation/javascript/get-api-key

Thanks.

### CODE REVIEW

**Comment by rajadain** [comment]
If you'd like me to change the casing of the new option let me know. I think I'd prefer `asClientId` but decided to follow the existing convention of the `googlekey`.

**Comment by Charmatzis** [comment]
Nice one!!!! But how can we test it, if it works?

**Comment by rajadain** [comment]
Good question. I know it is working because I'm using it for an internal project, but that doesn't help me prove it to those who don't have access to it. I wonder if we can find an open source project that uses a Client ID to test with ...

**Comment by Charmatzis** [comment]
That's right. Since I find a little bit time I try to merge the request with a test and give a big update. THX, again. 
PS. If you want to change anything else I am open to any changes!!!

**Comment by rajadain** [comment]
I would also add that the change is simply following [the documentation in google-maps](https://github.com/Carrooi/Js-GoogleMapsLoader#business-api-client).

**Comment by rajadain** [comment]
We may also want to upgrade the Google Maps API version to 3.25 [here](https://github.com/Charmatzis/react-leaflet-google/blob/master/src/leaflet.google.js#L8). Or make it configurable. The currently hard-coded one has been [retired](https://developers.google.com/maps/documentation/javascript/error-messages#retired-version).

**Pull request merged**
